/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PeaquisarCustoPanel.java
 *
 * Created on 09/05/2013, 21:11:59
 */
package br.com.generico.panel;

import br.com.generico.dao.CustoDao;
import br.com.generico.to.Custo;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.AbstractTableModel;
import org.apache.log4j.Logger;

/**
 *
 * @author marcos.celio
 */
public class PesquisarCustoPanel extends javax.swing.JPanel {

    private static SimpleDateFormat formataData = new SimpleDateFormat("dd/MM/yyyy");
    private static PesquisaCustoTableModel model;
    private NumberFormat formataMoeda = new DecimalFormat("##.##");
    private static Logger logger = Logger.getLogger(PesquisarCustoPanel.class.getName());

    /**
     * Creates new form PeaquisarCustoPanel
     */
    public PesquisarCustoPanel() {
        initComponents();
    }

    class PesquisaCustoTableModel extends AbstractTableModel {
        //private Object[][] data = {};

        List<Custo> data = new ArrayList<Custo>();
        private String[] columns = {"Nome", "Descrição", "Data", "Valor"};

        public String getColumnName(int column) {
            return columns[column];
        }

        public int getRowCount() {
            return data.size();
        }

        public int getColumnCount() {
            return columns.length;
        }

        public Object getValueAt(int rowNum, int colNum) {
            Custo custo = data.get(rowNum);

            if (colNum == 0) {
                return (custo.getNome() != null ? custo.getNome().trim() : "");
            } else if (colNum == 1) {
                return (custo.getDescricao() != null ? custo.getDescricao().trim() : "");
            } else if (colNum == 2) {
                if(custo.getData() == null || custo.getData().equals("")){
                    return "";
                }
                return formataData.format(custo.getData());
            } else if (colNum == 3) {
                return formataMoeda.format(custo.getValor());
            }
            return null;
        }

        public boolean isCellEditable(int row, int column) {
            return false;
        }

        public Class getColumnClass(int column) {
            return String.class;
        }

        public void setRows(List<Custo> data) {
            this.data = data;
        }

        public List<Custo> getData() {
            return data;
        }

        public void setValueAt(Object o, int row, int column) {
            try {
                Custo rowObj = data.get(row);
                if (column == 0) {
                    rowObj.setNome(o.toString());
                } else if (column == 1) {
                    rowObj.setDescricao(o.toString());
                } else if (column == 2) {
                    rowObj.setData(formataData.parse(o.toString()));
                } else if (column == 3) {
                    rowObj.setValor(Double.parseDouble(o.toString().trim().replace(",", ".")));
                }
            } catch (Exception e) {
                logger.error("Erro neste ponto:", e);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mes = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        ano = new javax.swing.JComboBox();

        jLabel1.setText("Mês:");

        mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Ano:");

        ano.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2013", "2014", "2015", "2016" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jButton1)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2)
                    .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    try {
        Custo custo = new Custo();

        int valorMes = mes.getSelectedIndex();
        int valorAno = Integer.parseInt(ano.getSelectedItem().toString());

        Calendar dataDe = Calendar.getInstance();
        dataDe.set(Calendar.DAY_OF_MONTH, 1);
        dataDe.set(Calendar.MONTH, valorMes);
        dataDe.set(Calendar.YEAR, valorAno);

        Calendar dataAte = Calendar.getInstance();
        dataAte.set(Calendar.DAY_OF_MONTH, 31);
        dataAte.set(Calendar.MONTH, valorMes);
        dataAte.set(Calendar.YEAR, valorAno);

        CustoDao custoDao = new CustoDao();

        List<Custo> resultado = custoDao.pesquisa(custo, formataData.format(dataDe.getTime()), formataData.format(dataAte.getTime()));

        if (resultado.isEmpty()) {
            JOptionPane.showMessageDialog(null, "A pesquisa não retornou registros.");
            return;
        }

        model = new PesquisaCustoTableModel();

        if (resultado != null) {
            Custo custoTotal = new Custo();
            Double total = 0.0;
            for (Custo o : resultado) {
                total += o.getValor();
            }
            custoTotal.setNome("TOTAL");
            custoTotal.setValor(total);
            resultado.add(custoTotal);
        }

        model.setRows(resultado);
        jTable1.setModel(model);
        jScrollPane1.setViewportView(jTable1);
        ListSelectionModel cellSelectionModel = jTable1.getSelectionModel();
        cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.setRowHeight(25);
        model.fireTableDataChanged();
    } catch (Exception e) {
        logger.error("Erro neste ponto:", e);
        JOptionPane.showMessageDialog(null, "Ocorreu um erro, por favor contate o desenvolvedor (Tel: 19-9354-5207).");
    }

}//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ano;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox mes;
    // End of variables declaration//GEN-END:variables
}
